### ISSUE TITLE
Crash when trying to load transaction pool

### ISSUE THREAD

**Issue by mtlynch** [NebulousLabs/Sia#1039]
I'm seeing a crash when I try to load the transaction pool. Repros pretty consistently. Anything I can do?
```
$ $GOPATH/bin/siad
Loading...
(1/7) Loading gateway...
(2/7) Loading consensus...
(3/7) Loading transaction pool...

unexpected fault address 0x33800040
fatal error: fault
[signal 0xb code=0x1 addr=0x33800040 pc=0x2de974]

goroutine 27 [running]:
runtime.throw(0x5bfb90, 0x5)
        /usr/local/go/src/runtime/panic.go:530 +0x78 fp=0x10dbd188 sp=0x10dbd17c
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:27 +0x280 fp=0x10dbd1b4 sp=0x10dbd188
github.com/NebulousLabs/bolt.(*Tx).rollback(0x10cd5900)
        /home/pi/go/src/github.com/NebulousLabs/bolt/tx.go:245 +0x70 fp=0x10dbd1c8 sp=0x10dbd1b8
github.com/NebulousLabs/bolt.(*Tx).Commit(0x10cd5900, 0x0, 0x0)
        /home/pi/go/src/github.com/NebulousLabs/bolt/tx.go:163 +0x1e8 fp=0x10dbd274 sp=0x10dbd1c8
github.com/NebulousLabs/bolt.(*DB).Update(0x10b8b8c0, 0x10dbd2b8, 0x0, 0x0)
        /home/pi/go/src/github.com/NebulousLabs/bolt/db.go:580 +0x110 fp=0x10dbd2a0 sp=0x10dbd274
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).addBlockToTree(0x10b7d080, 0x0, 0x973c0000, 0x1fe9ee9c, 0x247b032f, 0xddf1f464, 0xefdfcc6a, 0x244c3aef, 0x5c415e3f, 0x356ab31f, ...)
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:183 +0xa8 fp=0x10dbd310 sp=0x10dbd2a0
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlock(0x10b7d080, 0x0, 0x973c0000, 0x1fe9ee9c, 0x247b032f, 0xddf1f464, 0xefdfcc6a, 0x244c3aef, 0x5c415e3f, 0x356ab31f, ...)
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:259 +0xf4 fp=0x10dbd3f0 sp=0x10dbd310
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedReceiveBlocks(0x10b7d080, 0x7533f460, 0x10b0a070, 0x0, 0x0)
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:214 +0x6b4 fp=0x10dbdd84 sp=0x10dbd3f0
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.threadedReceiveBlocks)-fm(0x7533f460, 0x10b0a070, 0x0, 0x0)
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:134 +0x3c fp=0x10dbdd9c sp=0x10dbdd84
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0x10be3b40, 0x10c34920, 0x12, 0x5ee610, 0xa, 0x10b0a060, 0x0, 0x0)
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:53 +0x3c4 fp=0x10dbde44 sp=0x10dbdd9c
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0x10b7d080)
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:476 +0x318 fp=0x10dbdf9c sp=0x10dbde44
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x10b7d080, 0x753c17d8, 0x10be3b40)
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:126 +0x1c fp=0x10dbdfb4 sp=0x10dbdf9c
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:990 +0x4 fp=0x10dbdfb4 sp=0x10dbdfb4
created by github.com/NebulousLabs/Sia/modules/consensus.New
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:140 +0x628

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0x10b7d1b8)
        /usr/local/go/src/runtime/sema.go:47 +0x24
sync.(*Mutex).Lock(0x10b7d1b4)
        /usr/local/go/src/sync/mutex.go:83 +0x1fc
github.com/NebulousLabs/demotemutex.(*DemoteMutex).Lock(0x10b7d1b4)
        /home/pi/go/src/github.com/NebulousLabs/demotemutex/demotemutex.go:57 +0x28
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).ConsensusSetPersistentSubscribe(0x10b7d080, 0x753c6bb8, 0x10c385f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:161 +0xf8
github.com/NebulousLabs/Sia/modules/transactionpool.New(0x753c28f8, 0x10b7d080, 0x753c17d8, 0x10be3b40, 0x2, 0x0, 0x0)
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/transactionpool.go:96 +0x2e0
main.startDaemon(0x6059c0, 0xe, 0x5b9390, 0x5, 0x5b9398, 0x5, 0x5bea78, 0x7, 0x0, 0x5ee8e0, ...)
        /home/pi/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:107 +0xac4
main.startDaemonCmd(0x10ba6300, 0x949640, 0x0, 0x0)
        /home/pi/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:204 +0x1a0
github.com/spf13/cobra.(*Command).execute(0x10ba6300, 0x10b680b0, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/spf13/cobra/command.go:569 +0x664
github.com/spf13/cobra.(*Command).ExecuteC(0x10ba6300, 0x10ba6300, 0x0, 0x0)
        /home/pi/go/src/github.com/spf13/cobra/command.go:656 +0x440
github.com/spf13/cobra.(*Command).Execute(0x10ba6300, 0x0, 0x0)
        /home/pi/go/src/github.com/spf13/cobra/command.go:615 +0x28
main.main()
        /home/pi/go/src/github.com/NebulousLabs/Sia/siad/main.go:84 +0x574

goroutine 17 [syscall, 7 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:990 +0x4

goroutine 20 [syscall, 7 minutes]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x190
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x14
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x30

goroutine 21 [sleep]:
time.Sleep(0xf8475800, 0xd)
        /usr/local/go/src/runtime/time.go:59 +0x104
github.com/NebulousLabs/Sia/sync.(*RWMutex).threadedDeadlockFinder(0x10be3b00)
        /home/pi/go/src/github.com/NebulousLabs/Sia/sync/lock.go:78 +0x4b8
created by github.com/NebulousLabs/Sia/sync.New
        /home/pi/go/src/github.com/NebulousLabs/Sia/sync/lock.go:47 +0xbc

goroutine 69 [semacquire]:
sync.runtime_Syncsemacquire(0x10f0c088)
        /usr/local/go/src/runtime/sema.go:241 +0x250
sync.(*Cond).Wait(0x10f0c080)
        /usr/local/go/src/sync/cond.go:63 +0xbc
github.com/inconshreveable/muxado/proto/buffer.(*Inbound).Read(0x10cde100, 0x10f16040, 0x4, 0x4, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/buffer/inbound.go:155 +0x448
github.com/inconshreveable/muxado/proto.(*Stream).Read(0x10f38000, 0x10f16040, 0x4, 0x4, 0x5a5ce8, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/stream.go:73 +0x50
io.ReadAtLeast(0x753ceda8, 0x10f38000, 0x10f16040, 0x4, 0x4, 0x4, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:297 +0xdc
io.ReadFull(0x753ceda8, 0x10f38000, 0x10f16040, 0x4, 0x4, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:315 +0x5c
github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).respond(0x10de0120)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:81 +0x13c
created by github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).Start
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:46 +0x78

goroutine 24 [select]:
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).threadedPeerManager(0x10be3b40)
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:307 +0x1cc
created by github.com/NebulousLabs/Sia/modules/gateway.New
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:153 +0x7d8

goroutine 25 [select, 2 minutes]:
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).threadedNodeManager(0x10be3b40)
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/nodes.go:174 +0x3d0
created by github.com/NebulousLabs/Sia/modules/gateway.New
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:154 +0x7f4

goroutine 26 [IO wait, 7 minutes]:
net.runtime_pollWait(0x753c2880, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0x10be3cf8, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x10be3cf8, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).accept(0x10be3cc0, 0x0, 0x763fd0c8, 0x10b0e0d0)
        /usr/local/go/src/net/fd_unix.go:426 +0x21c
net.(*TCPListener).AcceptTCP(0x10b68e50, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:254 +0x4c
net.(*TCPListener).Accept(0x10b68e50, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:264 +0x34
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).listen(0x10be3b40)
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:117 +0x3c
created by github.com/NebulousLabs/Sia/modules/gateway.New
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:157 +0x810

goroutine 78 [semacquire]:
sync.runtime_Syncsemacquire(0x10eee028)
        /usr/local/go/src/runtime/sema.go:241 +0x250
sync.(*Cond).Wait(0x10eee020)
        /usr/local/go/src/sync/cond.go:63 +0xbc
github.com/inconshreveable/muxado/proto/buffer.(*Inbound).Read(0x10ca0000, 0x10c9e020, 0x4, 0x4, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/buffer/inbound.go:155 +0x448
github.com/inconshreveable/muxado/proto.(*Stream).Read(0x10f38050, 0x10c9e020, 0x4, 0x4, 0x5a5ce8, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/stream.go:73 +0x50
io.ReadAtLeast(0x753ceda8, 0x10f38050, 0x10c9e020, 0x4, 0x4, 0x4, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:297 +0xdc
io.ReadFull(0x753ceda8, 0x10f38050, 0x10c9e020, 0x4, 0x4, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:315 +0x5c
github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).respond(0x10e68200)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:81 +0x13c
created by github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).Start
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:46 +0x78

goroutine 102 [semacquire]:
sync.runtime_Syncsemacquire(0x10c355c8)
        /usr/local/go/src/runtime/sema.go:241 +0x250
sync.(*Cond).Wait(0x10c355c0)
        /usr/local/go/src/sync/cond.go:63 +0xbc
github.com/inconshreveable/muxado/proto/buffer.(*Inbound).Read(0x10cdd500, 0x10d82000, 0x4, 0x4, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/buffer/inbound.go:155 +0x448
github.com/inconshreveable/muxado/proto.(*Stream).Read(0x10f18aa0, 0x10d82000, 0x4, 0x4, 0x5a5ce8, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/stream.go:73 +0x50
io.ReadAtLeast(0x753ceda8, 0x10f18aa0, 0x10d82000, 0x4, 0x4, 0x4, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:297 +0xdc
io.ReadFull(0x753ceda8, 0x10f18aa0, 0x10d82000, 0x4, 0x4, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:315 +0x5c
github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).respond(0x11062320)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:81 +0x13c
created by github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).Start
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:46 +0x78

goroutine 70 [sleep]:
time.Sleep(0xb2d05e00, 0x0)
        /usr/local/go/src/runtime/time.go:59 +0x104
github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).request(0x10de0120)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:107 +0xfc
created by github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).Start
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:47 +0x94

goroutine 71 [select]:
github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).check(0x10de0120)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:57 +0x160
created by github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).Start
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:48 +0xb0

goroutine 72 [IO wait]:
net.runtime_pollWait(0x753c2628, 0x72, 0x10c9e098)
        /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0x10ca0078, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x10ca0078, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).Read(0x10ca0040, 0x10c9e098, 0x8, 0x8, 0x0, 0x753bd018, 0x10b6c000)
        /usr/local/go/src/net/fd_unix.go:250 +0x1c4
net.(*conn).Read(0x10c3e000, 0x10c9e098, 0x8, 0x8, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xc8
github.com/inconshreveable/muxado/proto/frame.(*BasicTransport).Read(0x10b82000, 0x10c9e098, 0x8, 0x8, 0x10c9e098, 0x0, 0x0)
        <autogenerated>:139 +0x90
io.ReadAtLeast(0x753ced58, 0x10b82000, 0x10c9e098, 0x8, 0x8, 0x8, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:297 +0xdc
io.ReadFull(0x753ced58, 0x10b82000, 0x10c9e098, 0x8, 0x8, 0x8, 0x0, 0x0)
        /usr/local/go/src/io/io.go:315 +0x5c
github.com/inconshreveable/muxado/proto/frame.(*BasicTransport).ReadFrame(0x10b82000, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/frame/transport.go:34 +0xb8
github.com/inconshreveable/muxado/proto.(*Session).reader(0x10c5a060)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/session.go:276 +0xac
created by github.com/inconshreveable/muxado/proto.NewSession
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/session.go:104 +0x57c

goroutine 73 [chan receive, 4 minutes]:
github.com/inconshreveable/muxado/proto.(*Session).Accept(0x10c5a060, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/session.go:159 +0x60
github.com/inconshreveable/muxado.(*sessionAdaptor).Accept(0x10c3e048, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/adaptor.go:33 +0x54
github.com/NebulousLabs/Sia/modules/gateway.(*peer).accept(0x10de01e0, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:65 +0x54
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).listenPeer(0x10be3b40, 0x10de01e0)
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:89 +0x1c
created by github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).addPeer
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:76 +0x6c

goroutine 79 [sleep]:
time.Sleep(0xb2d05e00, 0x0)
        /usr/local/go/src/runtime/time.go:59 +0x104
github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).request(0x10e68200)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:107 +0xfc
created by github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).Start
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:47 +0x94

goroutine 80 [select]:
github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).check(0x10e68200)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:57 +0x160
created by github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).Start
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:48 +0xb0

goroutine 81 [IO wait]:
net.runtime_pollWait(0x753c24c0, 0x72, 0x10c9a0e8)
        /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0x10e6a078, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x10e6a078, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).Read(0x10e6a040, 0x10c9a0e8, 0x8, 0x8, 0x0, 0x753bd018, 0x10b6c000)
        /usr/local/go/src/net/fd_unix.go:250 +0x1c4
net.(*conn).Read(0x10b0a090, 0x10c9a0e8, 0x8, 0x8, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xc8
github.com/inconshreveable/muxado/proto/frame.(*BasicTransport).Read(0x10b820a0, 0x10c9a0e8, 0x8, 0x8, 0x5a6188, 0x0, 0x0)
        <autogenerated>:139 +0x90
io.ReadAtLeast(0x753ced58, 0x10b820a0, 0x10c9a0e8, 0x8, 0x8, 0x8, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:297 +0xdc
io.ReadFull(0x753ced58, 0x10b820a0, 0x10c9a0e8, 0x8, 0x8, 0x8, 0x0, 0x0)
        /usr/local/go/src/io/io.go:315 +0x5c
github.com/inconshreveable/muxado/proto/frame.(*BasicTransport).ReadFrame(0x10b820a0, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/frame/transport.go:34 +0xb8
github.com/inconshreveable/muxado/proto.(*Session).reader(0x10e6c0c0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/session.go:276 +0xac
created by github.com/inconshreveable/muxado/proto.NewSession
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/session.go:104 +0x57c

goroutine 82 [chan receive, 4 minutes]:
github.com/inconshreveable/muxado/proto.(*Session).Accept(0x10e6c0c0, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/session.go:159 +0x60
github.com/inconshreveable/muxado.(*sessionAdaptor).Accept(0x10b0a0d0, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/adaptor.go:33 +0x54
github.com/NebulousLabs/Sia/modules/gateway.(*peer).accept(0x10e682c0, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:65 +0x54
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).listenPeer(0x10be3b40, 0x10e682c0)
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:89 +0x1c
created by github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).addPeer
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:76 +0x6c

goroutine 56 [semacquire]:
sync.runtime_Syncsemacquire(0x1105a028)
        /usr/local/go/src/runtime/sema.go:241 +0x250
sync.(*Cond).Wait(0x1105a020)
        /usr/local/go/src/sync/cond.go:63 +0xbc
github.com/inconshreveable/muxado/proto/buffer.(*Inbound).Read(0x10e160c0, 0x10cc6030, 0x4, 0x4, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/buffer/inbound.go:155 +0x448
github.com/inconshreveable/muxado/proto.(*Stream).Read(0x10c38140, 0x10cc6030, 0x4, 0x4, 0x5a5ce8, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/stream.go:73 +0x50
io.ReadAtLeast(0x753ceda8, 0x10c38140, 0x10cc6030, 0x4, 0x4, 0x4, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:297 +0xdc
io.ReadFull(0x753ceda8, 0x10c38140, 0x10cc6030, 0x4, 0x4, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:315 +0x5c
github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).respond(0x10ccfe60)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:81 +0x13c
created by github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).Start
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:46 +0x78

goroutine 57 [sleep]:
time.Sleep(0xb2d05e00, 0x0)
        /usr/local/go/src/runtime/time.go:59 +0x104
github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).request(0x10ccfe60)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:107 +0xfc
created by github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).Start
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:47 +0x94

goroutine 58 [select]:
github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).check(0x10ccfe60)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:57 +0x160
created by github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).Start
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:48 +0xb0

goroutine 59 [IO wait]:
net.runtime_pollWait(0x753c2178, 0x72, 0x10cea050)
        /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0x10cde0f8, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x10cde0f8, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).Read(0x10cde0c0, 0x10cea050, 0x8, 0x8, 0x0, 0x753bd018, 0x10b6c000)
        /usr/local/go/src/net/fd_unix.go:250 +0x1c4
net.(*conn).Read(0x10b0a0a8, 0x10cea050, 0x8, 0x8, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xc8
github.com/inconshreveable/muxado/proto/frame.(*BasicTransport).Read(0x10b82140, 0x10cea050, 0x8, 0x8, 0x10cea050, 0x0, 0x0)
        <autogenerated>:139 +0x90
io.ReadAtLeast(0x753ced58, 0x10b82140, 0x10cea050, 0x8, 0x8, 0x8, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:297 +0xdc
io.ReadFull(0x753ced58, 0x10b82140, 0x10cea050, 0x8, 0x8, 0x8, 0x0, 0x0)
        /usr/local/go/src/io/io.go:315 +0x5c
github.com/inconshreveable/muxado/proto/frame.(*BasicTransport).ReadFrame(0x10b82140, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/frame/transport.go:34 +0xb8
github.com/inconshreveable/muxado/proto.(*Session).reader(0x10c5a000)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/session.go:276 +0xac
created by github.com/inconshreveable/muxado/proto.NewSession
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/session.go:104 +0x57c

goroutine 60 [chan receive, 4 minutes]:
github.com/inconshreveable/muxado/proto.(*Session).Accept(0x10c5a000, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/session.go:159 +0x60
github.com/inconshreveable/muxado.(*sessionAdaptor).Accept(0x10b0a0f8, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/adaptor.go:33 +0x54
github.com/NebulousLabs/Sia/modules/gateway.(*peer).accept(0x10ccff20, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:65 +0x54
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).listenPeer(0x10be3b40, 0x10ccff20)
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:89 +0x1c
created by github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).addPeer
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:76 +0x6c

goroutine 383 [semacquire]:
sync.runtime_Syncsemacquire(0x10eee0e8)
        /usr/local/go/src/runtime/sema.go:241 +0x250
sync.(*Cond).Wait(0x10eee0e0)
        /usr/local/go/src/sync/cond.go:63 +0xbc
github.com/inconshreveable/muxado/proto/buffer.(*Inbound).Read(0x1120e000, 0x10f78040, 0x4, 0x4, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/buffer/inbound.go:155 +0x448
github.com/inconshreveable/muxado/proto.(*Stream).Read(0x10fc0230, 0x10f78040, 0x4, 0x4, 0x5a5ce8, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/stream.go:73 +0x50
io.ReadAtLeast(0x753ceda8, 0x10fc0230, 0x10f78040, 0x4, 0x4, 0x4, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:297 +0xdc
io.ReadFull(0x753ceda8, 0x10fc0230, 0x10f78040, 0x4, 0x4, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:315 +0x5c
github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).respond(0x10eec120)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:81 +0x13c
created by github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).Start
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:46 +0x78

goroutine 823 [chan receive]:
github.com/inconshreveable/muxado/proto.(*Session).Accept(0x10bc6000, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/session.go:159 +0x60
github.com/inconshreveable/muxado.(*sessionAdaptor).Accept(0x10c86068, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/adaptor.go:33 +0x54
github.com/NebulousLabs/Sia/modules/gateway.(*peer).accept(0x1119e200, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:65 +0x54
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).listenPeer(0x10be3b40, 0x1119e200)
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:89 +0x1c
created by github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).addPeer
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:76 +0x6c

goroutine 821 [select]:
github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).check(0x1119e140)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:57 +0x160
created by github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).Start
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:48 +0xb0

goroutine 820 [sleep]:
time.Sleep(0xb2d05e00, 0x0)
        /usr/local/go/src/runtime/time.go:59 +0x104
github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).request(0x1119e140)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:107 +0xfc
created by github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).Start
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:47 +0x94

goroutine 822 [IO wait]:
net.runtime_pollWait(0x753c25b0, 0x72, 0x110ec068)
        /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0x1120e0f8, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x1120e0f8, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).Read(0x1120e0c0, 0x110ec068, 0x8, 0x8, 0x0, 0x753bd018, 0x10b6c000)
        /usr/local/go/src/net/fd_unix.go:250 +0x1c4
net.(*conn).Read(0x10c86008, 0x110ec068, 0x8, 0x8, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xc8
github.com/inconshreveable/muxado/proto/frame.(*BasicTransport).Read(0x10d2e000, 0x110ec068, 0x8, 0x8, 0x110ec068, 0x0, 0x0)
        <autogenerated>:139 +0x90
io.ReadAtLeast(0x753ced58, 0x10d2e000, 0x110ec068, 0x8, 0x8, 0x8, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:297 +0xdc
io.ReadFull(0x753ced58, 0x10d2e000, 0x110ec068, 0x8, 0x8, 0x8, 0x0, 0x0)
        /usr/local/go/src/io/io.go:315 +0x5c
github.com/inconshreveable/muxado/proto/frame.(*BasicTransport).ReadFrame(0x10d2e000, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/frame/transport.go:34 +0xb8
github.com/inconshreveable/muxado/proto.(*Session).reader(0x10bc6000)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/session.go:276 +0xac
created by github.com/inconshreveable/muxado/proto.NewSession
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/session.go:104 +0x57c

goroutine 103 [sleep]:
time.Sleep(0xb2d05e00, 0x0)
        /usr/local/go/src/runtime/time.go:59 +0x104
github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).request(0x11062320)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:107 +0xfc
created by github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).Start
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:47 +0x94

goroutine 104 [select]:
github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).check(0x11062320)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:57 +0x160
created by github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).Start
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:48 +0xb0

goroutine 105 [IO wait]:
net.runtime_pollWait(0x753c2088, 0x72, 0x10cb00e8)
        /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0x10d0a138, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x10d0a138, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).Read(0x10d0a100, 0x10cb00e8, 0x8, 0x8, 0x0, 0x753bd018, 0x10b6c000)
        /usr/local/go/src/net/fd_unix.go:250 +0x1c4
net.(*conn).Read(0x10c3e020, 0x10cb00e8, 0x8, 0x8, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xc8
github.com/inconshreveable/muxado/proto/frame.(*BasicTransport).Read(0x10b82320, 0x10cb00e8, 0x8, 0x8, 0x10cb00e8, 0x0, 0x0)
        <autogenerated>:139 +0x90
io.ReadAtLeast(0x753ced58, 0x10b82320, 0x10cb00e8, 0x8, 0x8, 0x8, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:297 +0xdc
io.ReadFull(0x753ced58, 0x10b82320, 0x10cb00e8, 0x8, 0x8, 0x8, 0x0, 0x0)
        /usr/local/go/src/io/io.go:315 +0x5c
github.com/inconshreveable/muxado/proto/frame.(*BasicTransport).ReadFrame(0x10b82320, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/frame/transport.go:34 +0xb8
github.com/inconshreveable/muxado/proto.(*Session).reader(0x10c8c120)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/session.go:276 +0xac
created by github.com/inconshreveable/muxado/proto.NewSession
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/session.go:104 +0x57c

goroutine 106 [chan receive, 4 minutes]:
github.com/inconshreveable/muxado/proto.(*Session).Accept(0x10c8c120, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/session.go:159 +0x60
github.com/inconshreveable/muxado.(*sessionAdaptor).Accept(0x10c3e0e0, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/adaptor.go:33 +0x54
github.com/NebulousLabs/Sia/modules/gateway.(*peer).accept(0x110623e0, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:65 +0x54
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).listenPeer(0x10be3b40, 0x110623e0)
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:89 +0x1c
created by github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).addPeer
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:76 +0x6c

goroutine 819 [semacquire]:
sync.runtime_Syncsemacquire(0x1119e288)
        /usr/local/go/src/runtime/sema.go:241 +0x250
sync.(*Cond).Wait(0x1119e280)
        /usr/local/go/src/sync/cond.go:63 +0xbc
github.com/inconshreveable/muxado/proto/buffer.(*Inbound).Read(0x11064240, 0x110ec0dc, 0x4, 0x4, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/buffer/inbound.go:155 +0x448
github.com/inconshreveable/muxado/proto.(*Stream).Read(0x10f39090, 0x110ec0dc, 0x4, 0x4, 0x5a5ce8, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/stream.go:73 +0x50
io.ReadAtLeast(0x753ceda8, 0x10f39090, 0x110ec0dc, 0x4, 0x4, 0x4, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:297 +0xdc
io.ReadFull(0x753ceda8, 0x10f39090, 0x110ec0dc, 0x4, 0x4, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:315 +0x5c
github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).respond(0x1119e140)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:81 +0x13c
created by github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).Start
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:46 +0x78

goroutine 209 [sleep]:
time.Sleep(0xb2d05e00, 0x0)
        /usr/local/go/src/runtime/time.go:59 +0x104
github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).request(0x10e555e0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:107 +0xfc
created by github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).Start
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:47 +0x94

goroutine 159 [semacquire]:
sync.runtime_Syncsemacquire(0x11132028)
        /usr/local/go/src/runtime/sema.go:241 +0x250
sync.(*Cond).Wait(0x11132020)
        /usr/local/go/src/sync/cond.go:63 +0xbc
github.com/inconshreveable/muxado/proto/buffer.(*Inbound).Read(0x10cd6080, 0x10ed6030, 0x4, 0x4, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/buffer/inbound.go:155 +0x448
github.com/inconshreveable/muxado/proto.(*Stream).Read(0x10f18190, 0x10ed6030, 0x4, 0x4, 0x5a5ce8, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/stream.go:73 +0x50
io.ReadAtLeast(0x753ceda8, 0x10f18190, 0x10ed6030, 0x4, 0x4, 0x4, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:297 +0xdc
io.ReadFull(0x753ceda8, 0x10f18190, 0x10ed6030, 0x4, 0x4, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:315 +0x5c
github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).respond(0x10df80a0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:81 +0x13c
created by github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).Start
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:46 +0x78

goroutine 208 [semacquire]:
sync.runtime_Syncsemacquire(0x10e55768)
        /usr/local/go/src/runtime/sema.go:241 +0x250
sync.(*Cond).Wait(0x10e55760)
        /usr/local/go/src/sync/cond.go:63 +0xbc
github.com/inconshreveable/muxado/proto/buffer.(*Inbound).Read(0x10cdc400, 0x10bfe000, 0x4, 0x4, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/buffer/inbound.go:155 +0x448
github.com/inconshreveable/muxado/proto.(*Stream).Read(0x10f38230, 0x10bfe000, 0x4, 0x4, 0x5a5ce8, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/stream.go:73 +0x50
io.ReadAtLeast(0x753ceda8, 0x10f38230, 0x10bfe000, 0x4, 0x4, 0x4, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:297 +0xdc
io.ReadFull(0x753ceda8, 0x10f38230, 0x10bfe000, 0x4, 0x4, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:315 +0x5c
github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).respond(0x10e555e0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:81 +0x13c
created by github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).Start
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:46 +0x78

goroutine 160 [semacquire]:
sync.runtime_Syncsemacquire(0x11178028)
        /usr/local/go/src/runtime/sema.go:241 +0x250
sync.(*Cond).Wait(0x11178020)
        /usr/local/go/src/sync/cond.go:63 +0xbc
github.com/inconshreveable/muxado/proto/buffer.(*Inbound).Read(0x11158280, 0x11002018, 0x4, 0x8, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/buffer/inbound.go:155 +0x448
github.com/inconshreveable/muxado/proto.(*Stream).Read(0x10f38550, 0x11002018, 0x4, 0x8, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/stream.go:73 +0x50
io.ReadAtLeast(0x753ceda8, 0x10f38550, 0x11002018, 0x4, 0x8, 0x4, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:297 +0xdc
io.ReadFull(0x753ceda8, 0x10f38550, 0x11002018, 0x4, 0x8, 0x4, 0x0, 0x0)
        /usr/local/go/src/io/io.go:315 +0x5c
encoding/binary.Read(0x753ceda8, 0x10f38550, 0x753cf068, 0x949640, 0x4b75d8, 0x11002010, 0x0, 0x0)
        /usr/local/go/src/encoding/binary/binary.go:152 +0xf8
github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).request(0x10df80a0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:114 +0x2a8
created by github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).Start
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:47 +0x94

goroutine 161 [select]:
github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).check(0x10df80a0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:57 +0x160
created by github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).Start
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:48 +0xb0

goroutine 194 [runnable]:
syscall.Syscall(0x3, 0x1b, 0x10cea090, 0x8, 0x8, 0x0, 0x0)
        /usr/local/go/src/syscall/asm_linux_arm.s:17 +0x8
syscall.read(0x1b, 0x10cea090, 0x8, 0x8, 0x72, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_arm.go:783 +0x78
syscall.Read(0x1b, 0x10cea090, 0x8, 0x8, 0x4, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_unix.go:161 +0x4c
net.(*netFD).Read(0x1120e040, 0x10cea090, 0x8, 0x8, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/fd_unix.go:246 +0x134
net.(*conn).Read(0x10c86048, 0x10cea090, 0x8, 0x8, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xc8
github.com/inconshreveable/muxado/proto/frame.(*BasicTransport).Read(0x10b82280, 0x10cea090, 0x8, 0x8, 0x10cea090, 0x0, 0x0)
        <autogenerated>:139 +0x90
io.ReadAtLeast(0x753ced58, 0x10b82280, 0x10cea090, 0x8, 0x8, 0x8, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:297 +0xdc
io.ReadFull(0x753ced58, 0x10b82280, 0x10cea090, 0x8, 0x8, 0x8, 0x0, 0x0)
        /usr/local/go/src/io/io.go:315 +0x5c
github.com/inconshreveable/muxado/proto/frame.(*BasicTransport).ReadFrame(0x10b82280, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/frame/transport.go:34 +0xb8
github.com/inconshreveable/muxado/proto.(*Session).reader(0x11166000)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/session.go:276 +0xac
created by github.com/inconshreveable/muxado/proto.NewSession
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/session.go:104 +0x57c

goroutine 195 [chan receive, 4 minutes]:
github.com/inconshreveable/muxado/proto.(*Session).Accept(0x11166000, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/session.go:159 +0x60
github.com/inconshreveable/muxado.(*sessionAdaptor).Accept(0x10b688b0, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/adaptor.go:33 +0x54
github.com/NebulousLabs/Sia/modules/gateway.(*peer).accept(0x10df8160, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:65 +0x54
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).listenPeer(0x10be3b40, 0x10df8160)
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:89 +0x1c
created by github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).addPeer
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:76 +0x6c

goroutine 226 [select]:
github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).check(0x10e555e0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:57 +0x160
created by github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).Start
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:48 +0xb0

goroutine 227 [IO wait]:
net.runtime_pollWait(0x753c1ea8, 0x72, 0x10f16298)
        /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0x10cdc1f8, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x10cdc1f8, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).Read(0x10cdc1c0, 0x10f16298, 0x8, 0x8, 0x0, 0x753bd018, 0x10b6c000)
        /usr/local/go/src/net/fd_unix.go:250 +0x1c4
net.(*conn).Read(0x10b680f8, 0x10f16298, 0x8, 0x8, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xc8
github.com/inconshreveable/muxado/proto/frame.(*BasicTransport).Read(0x10b823c0, 0x10f16298, 0x8, 0x8, 0x10f16298, 0x0, 0x0)
        <autogenerated>:139 +0x90
io.ReadAtLeast(0x753ced58, 0x10b823c0, 0x10f16298, 0x8, 0x8, 0x8, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:297 +0xdc
io.ReadFull(0x753ced58, 0x10b823c0, 0x10f16298, 0x8, 0x8, 0x8, 0x0, 0x0)
        /usr/local/go/src/io/io.go:315 +0x5c
github.com/inconshreveable/muxado/proto/frame.(*BasicTransport).ReadFrame(0x10b823c0, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/frame/transport.go:34 +0xb8
github.com/inconshreveable/muxado/proto.(*Session).reader(0x10ef20c0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/session.go:276 +0xac
created by github.com/inconshreveable/muxado/proto.NewSession
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/session.go:104 +0x57c

goroutine 228 [chan receive, 4 minutes]:
github.com/inconshreveable/muxado/proto.(*Session).Accept(0x10ef20c0, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/session.go:159 +0x60
github.com/inconshreveable/muxado.(*sessionAdaptor).Accept(0x10b68580, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/adaptor.go:33 +0x54
github.com/NebulousLabs/Sia/modules/gateway.(*peer).accept(0x10e556a0, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:65 +0x54
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).listenPeer(0x10be3b40, 0x10e556a0)
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:89 +0x1c
created by github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).addPeer
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:76 +0x6c

goroutine 384 [sleep]:
time.Sleep(0xb2d05e00, 0x0)
        /usr/local/go/src/runtime/time.go:59 +0x104
github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).request(0x10eec120)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:107 +0xfc
created by github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).Start
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:47 +0x94

goroutine 385 [select]:
github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).check(0x10eec120)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:57 +0x160
created by github.com/inconshreveable/muxado/proto/ext.(*Heartbeat).Start
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/ext/heartbeat.go:48 +0xb0

goroutine 418 [IO wait]:
net.runtime_pollWait(0x753c2790, 0x72, 0x1105e058)
        /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0x10cdc078, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x10cdc078, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).Read(0x10cdc040, 0x1105e058, 0x8, 0x8, 0x0, 0x753bd018, 0x10b6c000)
        /usr/local/go/src/net/fd_unix.go:250 +0x1c4
net.(*conn).Read(0x10b680f0, 0x1105e058, 0x8, 0x8, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xc8
github.com/inconshreveable/muxado/proto/frame.(*BasicTransport).Read(0x10b82460, 0x1105e058, 0x8, 0x8, 0x1105e058, 0x0, 0x0)
        <autogenerated>:139 +0x90
io.ReadAtLeast(0x753ced58, 0x10b82460, 0x1105e058, 0x8, 0x8, 0x8, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:297 +0xdc
io.ReadFull(0x753ced58, 0x10b82460, 0x1105e058, 0x8, 0x8, 0x8, 0x0, 0x0)
        /usr/local/go/src/io/io.go:315 +0x5c
github.com/inconshreveable/muxado/proto/frame.(*BasicTransport).ReadFrame(0x10b82460, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/frame/transport.go:34 +0xb8
github.com/inconshreveable/muxado/proto.(*Session).reader(0x10c08000)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/session.go:276 +0xac
created by github.com/inconshreveable/muxado/proto.NewSession
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/session.go:104 +0x57c

goroutine 419 [chan receive, 4 minutes]:
github.com/inconshreveable/muxado/proto.(*Session).Accept(0x10c08000, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/proto/session.go:159 +0x60
github.com/inconshreveable/muxado.(*sessionAdaptor).Accept(0x10c3e160, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/inconshreveable/muxado/adaptor.go:33 +0x54
github.com/NebulousLabs/Sia/modules/gateway.(*peer).accept(0x10eec1e0, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:65 +0x54
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).listenPeer(0x10be3b40, 0x10eec1e0)
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:89 +0x1c
created by github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).addPeer
        /home/pi/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:76 +0x6c
```

**Comment by mtlynch** [comment]
Occurs on 5b5aca3b2ccc1a99a7568f0122ce0e8ae79e394c

**Comment by DavidVorick** [comment]
Thanks for the report, will look into it in greater depth in the next few days.

**Comment by DavidVorick** [comment]
Checking in, I believe this is the result of a bug in boltdb which has recently been fixed. I will wait to close the issue until we've merged the bugfix into our repo.

**Comment by lukechampine** [comment]
our fork is now up to date with the bolt master.

**Comment by mtlynch** [comment]
I'm still seeing this crash as of d73346719eae2f0cf0821cbcb6e8b45ae7714359

https://gist.github.com/mtlynch/9b74190189a1775274ec3bbfe060024c

Happened within a few thousand blocks of 34,868.

Can you re-open?

**Comment by lukechampine** [comment]
did you rerun `make dependencies`?

**Comment by mtlynch** [comment]
I did a clean reinstall:

```bash
$ rm -rf $GOPATH/*
$ go get -u github.com/NebulousLabs/Sia/...
$GOPATH/bin/siad
```

**Comment by lukechampine** [comment]
what is the output of `uname -a`? Seems like it may be specific to your architecture

**Comment by mtlynch** [comment]
This is on a Raspberry Pi 3

```
$ uname -r
4.4.9-v7+
```

**Comment by lukechampine** [comment]
interesting. It looks like the bolt transaction is succeeding, but failing to commit. The error is caused by `tx.root.spill()`. Try inserting the following in `$GOPATH/src/github.com/NebulousLabs/bolt/tx.go:163`:
```diff
	// spill data onto dirty pages.
	startTime = time.Now()
	if err := tx.root.spill(); err != nil {
+		println("Spill error:", err.Error())
		tx.rollback()
		return err
	}
```
Even more helpful would be to add `println`s for each error in the `spill` function (`bucket.go`). I'm not sure if I'll be able to figure out what's going based on those errors, but the Bolt maintainers might.

Unfortunately, it seems like this bug may take a long time to reproduce. From what I can tell, it occurs when the `ConsensusSet` is doing IBD concurrently with the transaction pool loading. So it's likely non-deterministic.

**Comment by mtlynch** [comment]
How to I rebuild `siad` against the modified `bolt`? Just `make dependencies`?

**Comment by mtlynch** [comment]
Okay, got it:

```
Spill error: mmap allocate error: cannot allocate memory
```

**Comment by DavidVorick** [comment]
> From what I can tell, it occurs when the ConsensusSet is doing IBD concurrently with the transaction pool loading. So it's likely non-deterministic.

Hmm. The transaction pool does multiple accesses to the consensus set while updating. Some combination of loading, receiving transactions, and processing incoming blocks may introduce thread un-safety which bolt was not designed to handle.

I can look at it more, it's entirely possible that there's a race condition somewhere which is causing this which is Sia's fault.

@mtlynch thanks for being persistent.

**Comment by lukechampine** [comment]
>`mmap allocate error: cannot allocate memory`

Ah, well that's pretty clear. Sounds like after a certain blockheight, bolt tries to increase the mmap'd size and it's too big for the RasPi to allocate. Googling around for "raspi mmap cannot allocate memory" is probably your best bet. There may be a workaround.

**Comment by DavidVorick** [comment]
Our consensus database is not compatible with 32bit devices :(

Maybe we should have `siad` refuse to start.
