### ISSUE TITLE
siad fails to form any contracts - unable to upload files

### ISSUE THREAD

**Issue by dymurray** [NebulousLabs/Sia#2546]
Bug Report
==========
Check to see if a bug report already exists.  If you still want to create a new issue please include the information below.

**Stack Trace or error message**
```
[dymurray]$ siac renter contracts                                                     │
No contracts have been formed.  
```

Error from minio when uploading a file:
```
ERRO[7005] Unexpected error, please report this issue at https://github.com/minio/minio/issues  cause=upload failed: not enough contracts to upload file: got 0, needed 20 source=[web-handlers.go:1098:toWebAPIError()]
```

**Environment**
* Sia version: 1.3.1
* OS: Fedora 25

**Any useful logs**
I'm mainly following [this guide](https://blog.sia.tech/api-quickstart-guide-f1d160c05235) except I also am using minio as a front end for uploading files. I have also just done straight curl requests. I have enough funds I'm not certain if this behavior is expected when not enough funds are allocated to the renter. Any information you could give me would be greatly appreciated. Thanks in advance!

**Comment by ChrisSchinnerl** [comment]
Can you post the contents of you `contractor.log`?

**Comment by dymurray** [comment]
@ChrisSchinnerl 
```
$ cat renter/contractor.log
2017/12/14 19:45:12.162363 contractor.go:194: STARTUP: Logging has started. Siad Version 1.3.1
2017/12/14 19:49:49.763902 contractor.go:230: SHUTDOWN: Logging has terminated.
2017/12/14 19:50:21.279342 contractor.go:194: STARTUP: Logging has started. Siad Version 1.3.1
2017/12/14 19:50:52.524975 contractor.go:230: SHUTDOWN: Logging has terminated.
2017/12/14 20:00:57.175916 contractor.go:194: STARTUP: Logging has started. Siad Version 1.3.1
2017/12/14 21:46:59.793858 contractor.go:230: SHUTDOWN: Logging has terminated.
2017/12/14 21:48:09.236364 contractor.go:194: STARTUP: Logging has started. Siad Version 1.3.1
2017/12/14 21:48:13.873272 contractor.go:230: SHUTDOWN: Logging has terminated.
2017/12/14 21:49:15.394037 contractor.go:194: STARTUP: Logging has started. Siad Version 1.3.1
2017/12/15 15:36:04.159226 allowance.go:60: INFO: setting allowance to {10 50 289 288}
```

**Comment by dymurray** [comment]
@ChrisSchinnerl I build `siad` from source yesterday 12/14.

**Comment by ChrisSchinnerl** [comment]
Your allowance seems to be extremely low (10 hastings). My guess is you wanted to set 10 SC and not 10 hastings in which case you need to multiple it by the siacoin precision as described in the "Uploading and Downloading files" section of the guide.
Keep in mind that shorter contract durations / renew windows might also make it harder to find hosts.

**Comment by dymurray** [comment]
@ChrisSchinnerl Okay thanks for the explanation. I did in fact have the allowance lower than I wanted. I updated the renter endpoint and now have this in the log:
```
2017/12/15 18:04:47.108533 allowance.go:60: INFO: setting allowance to {1000000000000000000000000000 50 4320 2160}
```

I've let it sit for over an hour now and still haven't seen any contracts. Is this expected?

**Comment by ChrisSchinnerl** [comment]
Ok this looks good now. Just let it sit for some time. It might be a bit slow atm due to the increased time between blocks. How many hosts does `siac hostdb` show you?

**Comment by dymurray** [comment]
`siac hostdb` actually returns: `No known active hosts`. I'm assuming this must be my fault somehow. Really appreciate your help and quick responses!

**Comment by ChrisSchinnerl** [comment]
Hosts announce themselves on the blockchain. Is your node synced?

**Comment by dymurray** [comment]
@ChrisSchinnerl Yeah my node is synced. 

Here's the GET request for consensus:
```
[dymurray@dymurray sia]$ curl -i -A "Sia-Agent" localhost:9980/consensus
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Fri, 15 Dec 2017 18:23:36 GMT
Content-Length: 263

{"synced":true,"height":137106,"currentblock":"0000000000000007a74458cfb8b91d7d7fab590f14d16d0072257f7e22ab3cdd","target":[0,0,0,0,0,0,0,43,165,76,234,216,132,41,88,155,108,149,204,25,249,179,120,67,19,169,194,45,225,71,76,168],"difficulty":"422647408473939000"}
```

**Comment by ChrisSchinnerl** [comment]
Hm... is there anything suspicious in your `hostdb.log` ?

**Comment by dymurray** [comment]
@ChrisSchinnerl 
```
2017/12/14 21:49:15.386925 hostdb.go:91: STARTUP: Logging has started. Siad Version 1.3.1
2017/12/14 21:49:15.394004 scan.go:339: Performing scan on 0 online hosts and 0 offline hosts.
2017/12/14 23:16:21.158451 scan.go:339: Performing scan on 0 online hosts and 0 offline hosts.
2017/12/15 06:32:27.994825 scan.go:339: Performing scan on 0 online hosts and 200 offline hosts.
2017/12/15 09:16:00.431505 scan.go:339: Performing scan on 0 online hosts and 200 offline hosts.
2017/12/15 14:13:18.854525 scan.go:339: Performing scan on 0 online hosts and 200 offline hosts.
```

**Comment by dymurray** [comment]
Interestingly a lot of the endpoints related to renter seem stale:
```
[dymurray@dymurray siad-docker]$ siac renter prices
Renter Prices (estimated):
  Fees for Creating a Set of Contracts:   0 H
  Download 1 TB:                          0 H
  Store 1 TB for 1 Month:                 0 H
  Upload 1 TB:                            0 H
```

I'm assuming that my hostdb list is either stale or pointing to invalid hosts. Just FYI I did have to manually add gateway addresses to get 1.3.1 working due to a known bug I was told. I'm not sure if that is significant but thought it was worth mentioning.

**Comment by ChrisSchinnerl** [comment]
Yeah that bug should be resolved in 1.3.1RC3. Scanning for hosts might take some time. Since you don't have active hosts you could try to force a rescan by stopping siad, deleting/renaming `hostdb.json` and restarting siad. Afterwards let it sit for a few hours to give it time to rescan all the hosts.

**Comment by dymurray** [comment]
Thanks @ChrisSchinnerl. I backed up `hostdb.json` and deleted it and restarted `siad`.  It took awhile to load renter and the file size is different so I know it created a new host list. I still see:
```
2017/12/15 19:20:25.333191 scan.go:339: Performing scan on 0 online hosts and 200 offline hosts.
```
But I am going to let this sit for a couple hours and will update the issue with my results.

Thanks for the help!

**Comment by DavidVorick** [comment]
Yes, unfortunately it currently takes Sia several hours to scan hosts and find good ones. If you have your renter running alongside the initial blockchain sync, you typically won't have any problems because the blockchain sync also takes several hours, and the scanning happens concurrently.

But if you already have a synced consensus database, then you still have to wait several hours for the host scanning to take effect.

This is something that's on our mid-short list to fix. You should be all good if you let it run overnight once. Once you have found a few hundred good hosts, you will be all set.

**Comment by dymurray** [comment]
@DavidVorick Thanks for the explanation, that makes sense. I'm going to let it continue running since I just started this node up yesterday and have been resetting it. I'll update the issue in a day or two if my issue is resolved.

Thank you guys for the prompt feedback!

**Comment by dymurray** [comment]
Just wanted to update this issue. I now have 115 active hosts so that problem is solved. I still have not formed any contracts yet and the node has been up for about 3 days now. Would you guys mind telling me if my allowance is just too low?
```
[dymurray@dymurray app]$ siac renter allowance
Allowance:
        Amount: 1 KS
        Period: 4320 blocks
```

I'm sill seeing `No contracts have been formed`. Thanks in advance.

**Comment by tbenz9** [comment]
I'm going to close this issue as there is no action item for the Sia developers left.  If you're still looking for help with usage I'd recommend asking in the #Help channel on the Sia Discord server.
